compatibility_date = "2022-06-25"

name = "risky-alerts"
type = "webpack"
account_id = "3360819ffc443f61bf601aaae41af18e"
workers_dev = true
route = ""
zone_id = "e9def7905d37ff77f118a254a6d8a1bf"

[site]
bucket = "./build"
entry-point = "workers-site"