account_id = "b27be28403d4c93295ffe1baf591566f"
compatibility_date = "2022-06-25"
name = "xxx"
route = ""
type = "webpack"
workers_dev = true
zone_id = "2ddde6f9273e3b04cdc256fbae79e5c2"
[site]
bucket = "./build"
entry-point = "workers-site"
